"""T2B.2 bit-exact regression gate for ``parquet_export``.

Compares the parquet bytes produced by the post-T2B.2 implementation
against frozen reference files captured from ``develop@eef6cf4``
(the spawn-point of the T2B.2 branch). Byte-for-byte equality is the
binding acceptance criterion of slice T2B.2 in master plan v3.2 §24:
the FeatureRegistry refactor must not perturb the on-disk output of
the lab's frozen dataset producer.

Reference fixtures live under :mod:`tests.fixtures`:

* ``parquet_export_golden_train.parquet`` train split
* ``parquet_export_golden_eval.parquet`` eval split

Both are generated by :mod:`scripts._t2b2_generate_golden_parquet`
which loads the legacy parquet_export from
``git show eef6cf4:protea/core/parquet_export.py`` so the reference
is anchored to the canonical pre-T2B.2 implementation. Re-generate
only when the canonical column set or fixture row intentionally
changes (which forces a SemVer bump on ``protea-contracts``).

The fixtures were regenerated in T-RES.1b when ``protea-contracts``
v0.3.0 added the four ``lineage`` columns to ``ALL_FEATURES``. The
legacy code path still produces the bytes (it reads the column set
from contracts at write time), so the eef6cf4 anchor remains valid;
only the on-disk reference rolls forward with the schema.

The input row factory mirrors :mod:`tests.test_parquet_export_boundary`
so the same fixture exercises both the boundary invariant and the
golden gate.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
from protea_contracts import ALL_FEATURES

from protea.core.parquet_export import (
    ParquetExportContext,
    export_reranker_parquets,
)

FIXTURE_DIR = Path(__file__).parent / "fixtures"
TRAIN_FIXTURE = FIXTURE_DIR / "parquet_export_golden_train.parquet"
EVAL_FIXTURE = FIXTURE_DIR / "parquet_export_golden_eval.parquet"

# The schema_sha that the legacy fixture pins. Recorded so the test
# fails loudly if the registry's column order ever drifts away from
# the contracts ``ALL_FEATURES`` order under which the golden was
# captured. Rolled forward in T-RES.1b: the prior
# ``"0d9b7219433f"`` (52 columns) is superseded by the value below
# after ``protea-contracts`` v0.3.0 added the lineage family. S3
# rolls it forward again: ``protea-contracts`` 0.4.0 added the
# 11-column interpro feature family (67 columns total), superseding
# the prior ``"6d97a624b8a7"``.
_LEGACY_FIXTURE_SHA = "ebb8af49befd"


def _full_feature_row() -> dict[str, object]:
    """Deterministic single-row shard input. Must match the row factory
    in :mod:`scripts._t2b2_generate_golden_parquet`.
    """
    row: dict[str, object] = {
        "protein_accession": "P12345",
        "go_id": "GO:0000001",
        "label": 0,
        "aspect": "P",
    }
    for col in ALL_FEATURES:
        if col in row:
            continue
        if col in {"qualifier", "evidence_code", "taxonomic_relation"}:
            row[col] = "x"
        else:
            row[col] = 0.0
    return row


def _write_shard(path: Path, rows: list[dict[str, object]]) -> Path:
    df = pd.DataFrame(rows) if rows else pd.DataFrame()
    df.to_parquet(path, index=False, compression="snappy")
    return path


def _build_ctx(stage_dir: Path) -> ParquetExportContext:
    """Reproduce the fixture-generation context bit-exactly.

    Any divergence here (k, ids, version strings) propagates into the
    manifest JSON only; the parquet bytes are independent of the
    manifest. The golden gate covers the parquets only because the
    manifest carries ``producer_git_sha`` which is a moving target.
    """
    train_shard = _write_shard(stage_dir / "_train_nk.parquet", [_full_feature_row()])
    eval_shard = _write_shard(stage_dir / "_eval_nk.parquet", [_full_feature_row()])
    return ParquetExportContext(
        stage_dir=stage_dir,
        split_files={"nk": [train_shard]},
        valid_split_versions=[(220, 221)],
        test_files={"nk": eval_shard},
        test_old_v=221,
        test_new_v=222,
        name="t2b2-golden",
        k=5,
        embedding_config_id="00000000-0000-0000-0000-000000000001",
        ontology_snapshot_id="00000000-0000-0000-0000-000000000002",
        annotation_source="goa",
        store=None,
        producer_version="t2b2",
        producer_git_sha="eef6cf4",
        validate_with_contracts=False,
    )


class TestGoldenParquetBitExact:
    """Bit-exact equality between the T2B.2 output and the eef6cf4 reference.

    Failure modes the test guards against:

    * Column-order drift introduced by FeatureRegistry vs the legacy
      ``ALL_FEATURES`` constant.
    * Dtype drift on any feature (e.g. ``float32`` vs ``float64``).
    * Compression / parquet-writer flag drift.
    * Reorder of reserved columns inside ``_reorder``.
    """

    def test_fixtures_are_committed(self) -> None:
        assert TRAIN_FIXTURE.exists(), (
            f"missing reference fixture {TRAIN_FIXTURE}. "
            "Regenerate via scripts/_t2b2_generate_golden_parquet.py."
        )
        assert EVAL_FIXTURE.exists(), (
            f"missing reference fixture {EVAL_FIXTURE}. "
            "Regenerate via scripts/_t2b2_generate_golden_parquet.py."
        )

    def test_train_parquet_byte_equal_to_reference(self, tmp_path: Path) -> None:
        ctx = _build_ctx(tmp_path)
        export_reranker_parquets(ctx)
        produced = (tmp_path / "train.parquet").read_bytes()
        reference = TRAIN_FIXTURE.read_bytes()
        assert produced == reference, (
            "train.parquet bytes diverged from the S3 interpro golden "
            f"(sha256[:12]=2f93adeaa892, schema_sha={_LEGACY_FIXTURE_SHA}). "
            f"produced_size={len(produced)} reference_size={len(reference)}. "
            "Either the FeatureRegistry column order drifted from "
            "protea_contracts.ALL_FEATURES, or parquet writer flags changed. "
            "Both are SemVer-major events; do not loosen this test."
        )

    def test_eval_parquet_byte_equal_to_reference(self, tmp_path: Path) -> None:
        ctx = _build_ctx(tmp_path)
        export_reranker_parquets(ctx)
        produced = (tmp_path / "eval.parquet").read_bytes()
        reference = EVAL_FIXTURE.read_bytes()
        assert produced == reference, (
            "eval.parquet bytes diverged from the S3 interpro golden "
            f"(sha256[:12]=fb49af9d1e16, schema_sha={_LEGACY_FIXTURE_SHA}). "
            f"produced_size={len(produced)} reference_size={len(reference)}. "
            "Same root causes as the train check; see that test for context."
        )

    def test_manifest_schema_sha_matches_legacy(self, tmp_path: Path) -> None:
        """The legacy schema_sha (json.dumps + sort_keys) is recomputed
        from the registry's name list. Pin the digest so a registry
        column reorder is caught before the parquet bytes diverge."""
        ctx = _build_ctx(tmp_path)
        result = export_reranker_parquets(ctx)
        assert result["schema_sha"] == _LEGACY_FIXTURE_SHA, (
            "schema_sha drifted from the eef6cf4 golden "
            f"({result['schema_sha']} vs {_LEGACY_FIXTURE_SHA}). "
            "FeatureRegistry.names() must preserve protea_contracts.ALL_FEATURES order."
        )
