from __future__ import annotations

import uuid
from unittest.mock import MagicMock, patch

import pytest

from protea.core.operations.load_goa_annotations import (
    LoadGOAAnnotationsOperation,
    LoadGOAAnnotationsPayload,
)

_noop_emit = lambda *_: None  # noqa: E731

_SNAPSHOT_ID = str(uuid.uuid4())

_GAF_SAMPLE = """\
!gaf-version: 2.2
!Generated by GO
UniProtKB\tP12345\tproteinA\tenables\tGO:0003824\tPMID:123\tIDA\t\t\t\t\tprotein\t\t20240101\tUniProt\t\t
UniProtKB\tQ67890\tproteinB\tinvolved_in\tGO:0008150\tPMID:456\tIEA\t\t\t\t\tprotein\t\t20240101\tUniProt\t\t
UniProtKB\tXXXXXX\tunknown\tenables\tGO:0003824\tPMID:789\tIDA\t\t\t\t\tprotein\t\t20240101\tUniProt\t\t
"""


class TestLoadGOAAnnotationsPayload:
    def test_valid(self) -> None:
        p = LoadGOAAnnotationsPayload.model_validate({
            "ontology_snapshot_id": _SNAPSHOT_ID,
            "gaf_url": "https://ftp.ebi.ac.uk/goa_human.gaf.gz",
            "source_version": "2024-03",
        })
        assert p.source_version == "2024-03"
        assert p.page_size == 10000

    def test_missing_required_raises(self) -> None:
        with pytest.raises(Exception):
            LoadGOAAnnotationsPayload.model_validate({
                "gaf_url": "https://example.org/goa.gaf.gz",
                "source_version": "2024-03",
            })

    def test_empty_snapshot_id_raises(self) -> None:
        with pytest.raises(Exception):
            LoadGOAAnnotationsPayload.model_validate({
                "ontology_snapshot_id": "  ",
                "gaf_url": "https://example.org/goa.gaf.gz",
                "source_version": "2024-03",
            })


class TestStoreBuffer:
    def _op(self) -> LoadGOAAnnotationsOperation:
        return LoadGOAAnnotationsOperation()

    def test_skips_unknown_accession(self) -> None:
        op = self._op()
        session = MagicMock()
        records = [
            {
                "accession": "UNKNOWN",
                "go_id": "GO:0003824",
                "qualifier": "enables",
                "evidence_code": "IDA",
                "db_reference": "PMID:1",
                "with_from": "",
                "assigned_by": "UniProt",
                "annotation_date": "20240101",
            }
        ]
        inserted, skipped = op._store_buffer(
            session,
            records,
            uuid.UUID(_SNAPSHOT_ID),
            valid_accessions={"P12345"},
            go_term_map={"GO:0003824": 1},
        )
        assert inserted == 0
        assert skipped == 1
        session.add_all.assert_not_called()

    def test_skips_unknown_go_term(self) -> None:
        op = self._op()
        session = MagicMock()
        records = [
            {
                "accession": "P12345",
                "go_id": "GO:9999999",
                "qualifier": "enables",
                "evidence_code": "IDA",
                "db_reference": "PMID:1",
                "with_from": "",
                "assigned_by": "UniProt",
                "annotation_date": "20240101",
            }
        ]
        inserted, skipped = op._store_buffer(
            session,
            records,
            uuid.UUID(_SNAPSHOT_ID),
            valid_accessions={"P12345"},
            go_term_map={"GO:0003824": 1},
        )
        assert inserted == 0
        assert skipped == 1

    def test_inserts_valid_records(self) -> None:
        op = self._op()
        session = MagicMock()
        records = [
            {
                "accession": "P12345",
                "go_id": "GO:0003824",
                "qualifier": "enables",
                "evidence_code": "IDA",
                "db_reference": "PMID:123",
                "with_from": "",
                "assigned_by": "UniProt",
                "annotation_date": "20240101",
            },
            {
                "accession": "Q67890",
                "go_id": "GO:0008150",
                "qualifier": "involved_in",
                "evidence_code": "IEA",
                "db_reference": "PMID:456",
                "with_from": "",
                "assigned_by": "UniProt",
                "annotation_date": "20240101",
            },
        ]
        inserted, skipped = op._store_buffer(
            session,
            records,
            uuid.UUID(_SNAPSHOT_ID),
            valid_accessions={"P12345", "Q67890"},
            go_term_map={"GO:0003824": 1, "GO:0008150": 2},
        )
        assert inserted == 2
        assert skipped == 0
        # Uses bulk pg_insert().on_conflict_do_nothing() instead of add_all
        session.execute.assert_called()
