"""add aspect to reranker_model and reranker_config to evaluation_result

Revision ID: 3505bfa74df6
Revises: 110a5b8cfbb9
Create Date: 2026-03-19 15:16:18.474851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3505bfa74df6'
down_revision: Union[str, Sequence[str], None] = '110a5b8cfbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_result', sa.Column('reranker_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reranker_model', sa.Column('aspect', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reranker_model', 'aspect')
    op.drop_column('evaluation_result', 'reranker_config')
    # ### end Alembic commands ###
