"""add reranker feature columns to go_prediction

Revision ID: 3884c47fe946
Revises: 5fc2eb0f986d
Create Date: 2026-03-18 13:40:17.716092

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3884c47fe946'
down_revision: str | Sequence[str] | None = '5fc2eb0f986d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('go_prediction', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.add_column('go_prediction', sa.Column('k_position', sa.Integer(), nullable=True))
    op.add_column('go_prediction', sa.Column('go_term_frequency', sa.Integer(), nullable=True))
    op.add_column('go_prediction', sa.Column('ref_annotation_density', sa.Integer(), nullable=True))
    op.add_column('go_prediction', sa.Column('neighbor_distance_std', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('go_prediction', 'neighbor_distance_std')
    op.drop_column('go_prediction', 'ref_annotation_density')
    op.drop_column('go_prediction', 'go_term_frequency')
    op.drop_column('go_prediction', 'k_position')
    op.drop_column('go_prediction', 'vote_count')
    # ### end Alembic commands ###
