"""add_parent_job_id

Revision ID: 4f38043a5e41
Revises: a1b2c3d4e5f6
Create Date: 2026-03-09 11:55:12.264352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f38043a5e41'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('parent_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_job_parent_job_id'), 'job', ['parent_job_id'], unique=False)
    op.create_foreign_key(None, 'job', 'job', ['parent_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_index(op.f('ix_job_parent_job_id'), table_name='job')
    op.drop_column('job', 'parent_job_id')
    # ### end Alembic commands ###
