"""add annotation tables

Revision ID: 91ef6ec08b11
Revises: 
Create Date: 2026-03-07 21:22:18.441709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91ef6ec08b11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('go_term',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('go_id', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('aspect', sa.String(length=1), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('is_obsolete', sa.Boolean(), nullable=False),
    sa.Column('ontology_snapshot_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('go_id', 'ontology_snapshot_id', name='uq_go_term_snapshot')
    )
    op.create_index(op.f('ix_go_term_go_id'), 'go_term', ['go_id'], unique=False)
    op.create_index(op.f('ix_go_term_ontology_snapshot_id'), 'go_term', ['ontology_snapshot_id'], unique=False)
    op.create_table('ontology_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obo_url', sa.String(), nullable=False),
    sa.Column('obo_version', sa.String(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ontology_snapshot_obo_version'), 'ontology_snapshot', ['obo_version'], unique=True)
    op.create_table('annotation_set',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.Column('ontology_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ontology_snapshot_id'], ['ontology_snapshot.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_set_job_id'), 'annotation_set', ['job_id'], unique=False)
    op.create_index(op.f('ix_annotation_set_ontology_snapshot_id'), 'annotation_set', ['ontology_snapshot_id'], unique=False)
    op.create_index(op.f('ix_annotation_set_source'), 'annotation_set', ['source'], unique=False)
    op.create_table('protein_go_annotation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('annotation_set_id', sa.UUID(), nullable=False),
    sa.Column('protein_accession', sa.String(), nullable=False),
    sa.Column('go_term_id', sa.BigInteger(), nullable=False),
    sa.Column('qualifier', sa.String(), nullable=True),
    sa.Column('evidence_code', sa.String(length=10), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('db_reference', sa.String(), nullable=True),
    sa.Column('with_from', sa.String(), nullable=True),
    sa.Column('annotation_date', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['go_term_id'], ['go_term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protein_accession'], ['protein.accession'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_set_id', 'protein_accession', 'go_term_id', 'evidence_code', name='uq_pga_set_protein_term_evidence')
    )
    op.create_index(op.f('ix_protein_go_annotation_annotation_set_id'), 'protein_go_annotation', ['annotation_set_id'], unique=False)
    op.create_index(op.f('ix_protein_go_annotation_evidence_code'), 'protein_go_annotation', ['evidence_code'], unique=False)
    op.create_index(op.f('ix_protein_go_annotation_go_term_id'), 'protein_go_annotation', ['go_term_id'], unique=False)
    op.create_index(op.f('ix_protein_go_annotation_protein_accession'), 'protein_go_annotation', ['protein_accession'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protein_go_annotation_protein_accession'), table_name='protein_go_annotation')
    op.drop_index(op.f('ix_protein_go_annotation_go_term_id'), table_name='protein_go_annotation')
    op.drop_index(op.f('ix_protein_go_annotation_evidence_code'), table_name='protein_go_annotation')
    op.drop_index(op.f('ix_protein_go_annotation_annotation_set_id'), table_name='protein_go_annotation')
    op.drop_table('protein_go_annotation')
    op.drop_index(op.f('ix_annotation_set_source'), table_name='annotation_set')
    op.drop_index(op.f('ix_annotation_set_ontology_snapshot_id'), table_name='annotation_set')
    op.drop_index(op.f('ix_annotation_set_job_id'), table_name='annotation_set')
    op.drop_table('annotation_set')
    op.drop_index(op.f('ix_ontology_snapshot_obo_version'), table_name='ontology_snapshot')
    op.drop_table('ontology_snapshot')
    op.drop_index(op.f('ix_go_term_ontology_snapshot_id'), table_name='go_term')
    op.drop_index(op.f('ix_go_term_go_id'), table_name='go_term')
    op.drop_table('go_term')
    # ### end Alembic commands ###
