"""initial_schema

Revision ID: cdd8510858db
Revises: 
Create Date: 2026-03-08 11:32:48.937483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdd8510858db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_backend', sa.String(), nullable=False),
    sa.Column('layer_indices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('layer_agg', sa.String(), nullable=False),
    sa.Column('pooling', sa.String(), nullable=False),
    sa.Column('normalize', sa.Boolean(), nullable=False),
    sa.Column('max_length', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_config_model_name'), 'embedding_config', ['model_name'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('queue_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_current', sa.BigInteger(), nullable=True),
    sa.Column('progress_total', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_created_at', 'job', ['created_at'], unique=False)
    op.create_index('ix_job_operation_created_at', 'job', ['operation', 'created_at'], unique=False)
    op.create_index('ix_job_status_created_at', 'job', ['status', 'created_at'], unique=False)
    op.create_table('ontology_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obo_url', sa.String(), nullable=False),
    sa.Column('obo_version', sa.String(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ontology_snapshot_obo_version'), 'ontology_snapshot', ['obo_version'], unique=True)
    op.create_table('protein_uniprot_metadata',
    sa.Column('canonical_accession', sa.String(), nullable=False),
    sa.Column('absorption', sa.Text(), nullable=True),
    sa.Column('active_site', sa.Text(), nullable=True),
    sa.Column('binding_site', sa.Text(), nullable=True),
    sa.Column('catalytic_activity', sa.Text(), nullable=True),
    sa.Column('cofactor', sa.Text(), nullable=True),
    sa.Column('dna_binding', sa.Text(), nullable=True),
    sa.Column('ec_number', sa.Text(), nullable=True),
    sa.Column('activity_regulation', sa.Text(), nullable=True),
    sa.Column('function_cc', sa.Text(), nullable=True),
    sa.Column('pathway', sa.Text(), nullable=True),
    sa.Column('kinetics', sa.Text(), nullable=True),
    sa.Column('ph_dependence', sa.Text(), nullable=True),
    sa.Column('redox_potential', sa.Text(), nullable=True),
    sa.Column('rhea_id', sa.Text(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('temperature_dependence', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('canonical_accession')
    )
    op.create_table('sequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('sequence_hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_sequence_hash'), 'sequence', ['sequence_hash'], unique=True)
    op.create_table('annotation_set',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.Column('ontology_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ontology_snapshot_id'], ['ontology_snapshot.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_set_job_id'), 'annotation_set', ['job_id'], unique=False)
    op.create_index(op.f('ix_annotation_set_ontology_snapshot_id'), 'annotation_set', ['ontology_snapshot_id'], unique=False)
    op.create_index(op.f('ix_annotation_set_source'), 'annotation_set', ['source'], unique=False)
    op.create_table('go_term',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('go_id', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('aspect', sa.String(length=1), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('is_obsolete', sa.Boolean(), nullable=False),
    sa.Column('ontology_snapshot_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ontology_snapshot_id'], ['ontology_snapshot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('go_id', 'ontology_snapshot_id', name='uq_go_term_snapshot')
    )
    op.create_index(op.f('ix_go_term_go_id'), 'go_term', ['go_id'], unique=False)
    op.create_index(op.f('ix_go_term_ontology_snapshot_id'), 'go_term', ['ontology_snapshot_id'], unique=False)
    op.create_table('job_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_event_event_ts_desc', 'job_event', ['event', 'ts'], unique=False)
    op.create_index('ix_job_event_job_id_ts_desc', 'job_event', ['job_id', 'ts'], unique=False)
    op.create_table('protein',
    sa.Column('accession', sa.String(), nullable=False),
    sa.Column('entry_name', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('canonical_accession', sa.String(), nullable=False),
    sa.Column('isoform_index', sa.Integer(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('taxonomy_id', sa.String(), nullable=True),
    sa.Column('organism', sa.String(), nullable=True),
    sa.Column('gene_name', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('accession')
    )
    op.create_index(op.f('ix_protein_canonical_accession'), 'protein', ['canonical_accession'], unique=False)
    op.create_index(op.f('ix_protein_entry_name'), 'protein', ['entry_name'], unique=False)
    op.create_index(op.f('ix_protein_reviewed'), 'protein', ['reviewed'], unique=False)
    op.create_index(op.f('ix_protein_sequence_id'), 'protein', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_protein_taxonomy_id'), 'protein', ['taxonomy_id'], unique=False)
    op.create_table('sequence_embedding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('embedding_config_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_config_id'], ['embedding_config.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', 'embedding_config_id', name='uq_seq_embedding_seq_config')
    )
    op.create_index(op.f('ix_sequence_embedding_embedding_config_id'), 'sequence_embedding', ['embedding_config_id'], unique=False)
    op.create_index(op.f('ix_sequence_embedding_sequence_id'), 'sequence_embedding', ['sequence_id'], unique=False)
    op.create_table('prediction_set',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding_config_id', sa.UUID(), nullable=False),
    sa.Column('annotation_set_id', sa.UUID(), nullable=False),
    sa.Column('ontology_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('limit_per_entry', sa.Integer(), nullable=False),
    sa.Column('distance_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_set.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['embedding_config_id'], ['embedding_config.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ontology_snapshot_id'], ['ontology_snapshot.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_set_annotation_set_id'), 'prediction_set', ['annotation_set_id'], unique=False)
    op.create_index(op.f('ix_prediction_set_embedding_config_id'), 'prediction_set', ['embedding_config_id'], unique=False)
    op.create_index(op.f('ix_prediction_set_ontology_snapshot_id'), 'prediction_set', ['ontology_snapshot_id'], unique=False)
    op.create_table('protein_go_annotation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('annotation_set_id', sa.UUID(), nullable=False),
    sa.Column('protein_accession', sa.String(), nullable=False),
    sa.Column('go_term_id', sa.BigInteger(), nullable=False),
    sa.Column('qualifier', sa.String(), nullable=True),
    sa.Column('evidence_code', sa.String(), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('db_reference', sa.String(), nullable=True),
    sa.Column('with_from', sa.String(), nullable=True),
    sa.Column('annotation_date', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['go_term_id'], ['go_term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protein_accession'], ['protein.accession'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_set_id', 'protein_accession', 'go_term_id', 'evidence_code', name='uq_pga_set_protein_term_evidence')
    )
    op.create_index(op.f('ix_protein_go_annotation_annotation_set_id'), 'protein_go_annotation', ['annotation_set_id'], unique=False)
    op.create_index(op.f('ix_protein_go_annotation_evidence_code'), 'protein_go_annotation', ['evidence_code'], unique=False)
    op.create_index(op.f('ix_protein_go_annotation_go_term_id'), 'protein_go_annotation', ['go_term_id'], unique=False)
    op.create_index(op.f('ix_protein_go_annotation_protein_accession'), 'protein_go_annotation', ['protein_accession'], unique=False)
    op.create_table('go_prediction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_set_id', sa.UUID(), nullable=False),
    sa.Column('protein_accession', sa.String(), nullable=False),
    sa.Column('go_term_id', sa.BigInteger(), nullable=False),
    sa.Column('ref_protein_accession', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('qualifier', sa.String(), nullable=True),
    sa.Column('evidence_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['go_term_id'], ['go_term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_set_id'], ['prediction_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protein_accession'], ['protein.accession'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_set_id', 'protein_accession', 'go_term_id', name='uq_go_prediction_set_protein_term')
    )
    op.create_index(op.f('ix_go_prediction_go_term_id'), 'go_prediction', ['go_term_id'], unique=False)
    op.create_index(op.f('ix_go_prediction_prediction_set_id'), 'go_prediction', ['prediction_set_id'], unique=False)
    op.create_index(op.f('ix_go_prediction_protein_accession'), 'go_prediction', ['protein_accession'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_go_prediction_protein_accession'), table_name='go_prediction')
    op.drop_index(op.f('ix_go_prediction_prediction_set_id'), table_name='go_prediction')
    op.drop_index(op.f('ix_go_prediction_go_term_id'), table_name='go_prediction')
    op.drop_table('go_prediction')
    op.drop_index(op.f('ix_protein_go_annotation_protein_accession'), table_name='protein_go_annotation')
    op.drop_index(op.f('ix_protein_go_annotation_go_term_id'), table_name='protein_go_annotation')
    op.drop_index(op.f('ix_protein_go_annotation_evidence_code'), table_name='protein_go_annotation')
    op.drop_index(op.f('ix_protein_go_annotation_annotation_set_id'), table_name='protein_go_annotation')
    op.drop_table('protein_go_annotation')
    op.drop_index(op.f('ix_prediction_set_ontology_snapshot_id'), table_name='prediction_set')
    op.drop_index(op.f('ix_prediction_set_embedding_config_id'), table_name='prediction_set')
    op.drop_index(op.f('ix_prediction_set_annotation_set_id'), table_name='prediction_set')
    op.drop_table('prediction_set')
    op.drop_index(op.f('ix_sequence_embedding_sequence_id'), table_name='sequence_embedding')
    op.drop_index(op.f('ix_sequence_embedding_embedding_config_id'), table_name='sequence_embedding')
    op.drop_table('sequence_embedding')
    op.drop_index(op.f('ix_protein_taxonomy_id'), table_name='protein')
    op.drop_index(op.f('ix_protein_sequence_id'), table_name='protein')
    op.drop_index(op.f('ix_protein_reviewed'), table_name='protein')
    op.drop_index(op.f('ix_protein_entry_name'), table_name='protein')
    op.drop_index(op.f('ix_protein_canonical_accession'), table_name='protein')
    op.drop_table('protein')
    op.drop_index('ix_job_event_job_id_ts_desc', table_name='job_event')
    op.drop_index('ix_job_event_event_ts_desc', table_name='job_event')
    op.drop_table('job_event')
    op.drop_index(op.f('ix_go_term_ontology_snapshot_id'), table_name='go_term')
    op.drop_index(op.f('ix_go_term_go_id'), table_name='go_term')
    op.drop_table('go_term')
    op.drop_index(op.f('ix_annotation_set_source'), table_name='annotation_set')
    op.drop_index(op.f('ix_annotation_set_ontology_snapshot_id'), table_name='annotation_set')
    op.drop_index(op.f('ix_annotation_set_job_id'), table_name='annotation_set')
    op.drop_table('annotation_set')
    op.drop_index(op.f('ix_sequence_sequence_hash'), table_name='sequence')
    op.drop_table('sequence')
    op.drop_table('protein_uniprot_metadata')
    op.drop_index(op.f('ix_ontology_snapshot_obo_version'), table_name='ontology_snapshot')
    op.drop_table('ontology_snapshot')
    op.drop_index('ix_job_status_created_at', table_name='job')
    op.drop_index('ix_job_operation_created_at', table_name='job')
    op.drop_index('ix_job_created_at', table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_embedding_config_model_name'), table_name='embedding_config')
    op.drop_table('embedding_config')
    # ### end Alembic commands ###
