"""add FK go_term ontology_snapshot

Revision ID: dc0cb8499090
Revises: 91ef6ec08b11
Create Date: 2026-03-07 21:25:39.485604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0cb8499090'
down_revision: Union[str, Sequence[str], None] = '91ef6ec08b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'go_term', 'ontology_snapshot', ['ontology_snapshot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'go_term', type_='foreignkey')
    # ### end Alembic commands ###
