{{- if .Values.amqp.internal }}
{{- $component := "rabbitmq" -}}
{{- $name := include "protea.componentName" (dict "ctx" . "component" $component) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "protea.componentLabels" (dict "ctx" . "component" $component) | nindent 4 }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "protea.selectorLabels" (dict "ctx" . "component" $component) | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "protea.componentLabels" (dict "ctx" . "component" $component) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "protea.selectorLabels" (dict "ctx" . "component" $component) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "protea.componentLabels" (dict "ctx" . "component" $component) | nindent 8 }}
    spec:
      {{- include "protea.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ $name }}
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
{{- end }}
