apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protea.componentName" (dict "ctx" . "component" "config") }}
  labels:
    {{- include "protea.componentLabels" (dict "ctx" . "component" "config") | nindent 4 }}
type: Opaque
stringData:
  PROTEA_DB_URL: {{ include "protea.databaseUrl" . | quote }}
  PROTEA_AMQP_URL: {{ include "protea.amqpUrl" . | quote }}
{{- if .Values.database.internal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protea.componentName" (dict "ctx" . "component" "postgres") }}
  labels:
    {{- include "protea.componentLabels" (dict "ctx" . "component" "postgres") | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
{{- end }}
{{- if .Values.amqp.internal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protea.componentName" (dict "ctx" . "component" "rabbitmq") }}
  labels:
    {{- include "protea.componentLabels" (dict "ctx" . "component" "rabbitmq") | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.amqp.user | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.amqp.password | quote }}
{{- end }}
{{- if .Values.objectStore.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protea.componentName" (dict "ctx" . "component" "minio") }}
  labels:
    {{- include "protea.componentLabels" (dict "ctx" . "component" "minio") | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.objectStore.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.objectStore.rootPassword | quote }}
{{- end }}
