#!/usr/bin/env python3
"""Cross-reference check: docs/source/ vs. docs/openapi.json (DS.3).

The authoritative documentation surface for route coverage is the
"Endpoints summary" table in docs/source/reference/api.rst plus all
inline route mentions across the docs tree.

The authoritative machine spec is docs/openapi.json (committed snapshot,
regenerated by scripts/generate_openapi.py / openapi-drift.yml).

This script:

1. Loads the committed OpenAPI snapshot and extracts (METHOD, path) pairs
   after stripping the /v1/ canonical prefix.  Path parameters are
   normalised to a generic ``{*}`` token so ``{job_id}`` == ``{id}``.

2. Scans docs/source/**/*.rst for inline route references.  The
   convention in PROTEA RSTs is plain inline code:
       ``GET /jobs/{id}``          (backtick-quoted)
       ``POST /jobs``
   This script also handles unquoted forms found in list-table rows:
       - ``GET``        /jobs/{id}    (method in one cell, path in next)

3. Compares the two normalised sets and exits non-zero when:
   - A route is cited in the docs but does NOT exist in the OpenAPI
     schema (stale / phantom route).  EXIT CODE 1.

   Routes that exist in OpenAPI but are not cited anywhere in the docs
   are reported as WARNINGS only (informational gap, not a hard failure)
   unless --strict-undocumented is passed.

Allowlist (internal / infrastructure routes that intentionally have no
doc coverage):

  /health        — liveness probe; not user-facing
  /health/ready  — readiness probe; not user-facing

Usage:
  python scripts/check_openapi_refs.py [--strict-undocumented] [paths...]

  paths  Optional override for RST search roots.
         Default: docs/source/

Exits 0 on success, 1 on phantom routes (docs reference non-existent route).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Route patterns used to detect method+path references in RST prose.
# ---------------------------------------------------------------------------

# Matches ``METHOD /path/...`` inside backtick inline-code spans.
# Captures the full route string including parameters like {id}.
_INLINE_ROUTE_RE = re.compile(
    r"``((?:GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\s+(/[^\s`]+))``",
    re.IGNORECASE,
)

# Matches bare (non-backtick-quoted) METHOD + path in list-table cells or
# plain prose, e.g.:  "- ``GET``" followed on the SAME line by a path.
# Used as a fallback for lines that split method and path into adjacent cells.
_CELL_METHOD_RE = re.compile(
    r"^\s*[-*]?\s*``(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)``\s+(/[^\s]+)",
    re.IGNORECASE,
)

# In the list-table in api.rst the path is on the NEXT row from the method.
# We handle that with a small two-line state machine below.

# HTTP methods we care about.
_METHODS = {"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"}

# ---------------------------------------------------------------------------
# Allowlist: routes in OpenAPI that are intentionally not documented.
# Each entry is a normalised path (after stripping /v1/ and collapsing
# path-parameter tokens to {*}).
# ---------------------------------------------------------------------------

# Format: frozenset of (METHOD, normalised_path)
_ALLOWLIST: frozenset[tuple[str, str]] = frozenset(
    [
        # Liveness probe — infrastructure, not a public API route.
        ("GET", "/health"),
        # Readiness probe — infrastructure, not a public API route.
        ("GET", "/health/ready"),
        # FastAPI serves the OpenAPI spec at /openapi.json automatically; it is
        # not listed in the paths section of the schema itself but docs reference it.
        ("GET", "/openapi.json"),
        # Retired endpoint (F0 / T0.6): LightGBM training was moved to
        # protea-reranker-lab.  train_reranker / train_reranker_auto are
        # unregistered.  Docs mention it only as historical context.
        ("POST", "/scoring/rerankers/train"),
        # howto_guides.rst uses {NK|LK|PK} as a shorthand for three separate
        # routes.  After normalisation this becomes /ground-truth-{*}.tsv which
        # does not match the three concrete paths in the schema.  The concrete
        # routes (/ground-truth-NK.tsv, -LK.tsv, -PK.tsv) ARE documented in the
        # api.rst endpoints-summary table and therefore covered elsewhere.
        ("GET", "/annotations/evaluation-sets/{*}/ground-truth-{*}.tsv"),
    ]
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_PARAM_TOKEN_RE = re.compile(r"\{[^}]+\}")


def normalise_path(raw: str) -> str:
    """Strip /v1/ prefix, query string, and collapse path-parameter tokens to ``{*}``.

    ``/v1/jobs/{job_id}``                            → ``/jobs/{*}``
    ``/jobs/{id}``                                   → ``/jobs/{*}``
    ``/scoring/prediction-sets/{id}/rerank.tsv?x=y`` → ``/scoring/prediction-sets/{*}/rerank.tsv``
    """
    path = raw.strip()
    # Strip query string (anything after the first "?").
    if "?" in path:
        path = path.split("?", 1)[0]
    # Strip /v1 prefix if present.
    if path.startswith("/v1/"):
        path = path[3:]
    elif path == "/v1":
        path = "/"
    # Normalise all {param} tokens to a generic placeholder.
    path = _PARAM_TOKEN_RE.sub("{*}", path)
    return path


def routes_from_openapi(openapi_path: Path) -> set[tuple[str, str]]:
    """Return a set of (METHOD, normalised_path) from the committed snapshot."""
    try:
        spec = json.loads(openapi_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"check_openapi_refs: ERROR reading {openapi_path}: {exc}", file=sys.stderr)
        sys.exit(2)

    routes: set[tuple[str, str]] = set()
    for raw_path, methods in spec.get("paths", {}).items():
        norm = normalise_path(raw_path)
        for method_key in methods:
            method = method_key.upper()
            if method in _METHODS:
                routes.add((method, norm))
    return routes


def routes_from_docs(search_roots: list[Path]) -> dict[tuple[str, str], list[tuple[Path, int]]]:
    """Return a mapping of (METHOD, normalised_path) → [(file, lineno)] from RST files."""
    found: dict[tuple[str, str], list[tuple[Path, int]]] = {}

    rst_files: list[Path] = []
    for root in search_roots:
        if root.is_file() and root.suffix == ".rst":
            rst_files.append(root)
        elif root.is_dir():
            rst_files.extend(sorted(root.rglob("*.rst")))

    for fpath in rst_files:
        lines = fpath.read_text(encoding="utf-8", errors="replace").splitlines()
        prev_method: str | None = None  # for two-line list-table rows

        for lineno, line in enumerate(lines, start=1):
            # Skip lines that are inside literal / code blocks (crude heuristic).
            # Full code-block tracking is overkill here; inline backtick quotes
            # already protect code samples from false positives.

            # 1) Inline: ``METHOD /path/...``  (most common)
            for m in _INLINE_ROUTE_RE.finditer(line):
                raw_method, raw_path = m.group(1).split(None, 1)
                method = raw_method.upper()
                norm = normalise_path(raw_path)
                key = (method, norm)
                found.setdefault(key, []).append((fpath, lineno))

            # 2) RST list-table rows in api.rst split method and path onto
            #    adjacent lines.  The format is:
            #      "   * - ``GET``"       ← method cell (first column of a new row)
            #      "     - ``/jobs``"     ← path cell  (second column, next line)
            #
            #    After strip():
            #      "* - ``GET``"
            #      "- ``/health``"
            stripped = line.strip()

            # RST list-table cell.  After strip(), method cell looks like:
            #   "* - ``GET``"    (first column of a new row: "* -" prefix)
            #   "- ``POST``"     (would not normally appear alone, but handle it)
            # Path cell looks like:
            #   "- ``/jobs``"    (second column: bare "- " prefix)
            #
            # Method cell: line starts with "* - ``METHOD``" or "- ``METHOD``"
            # where METHOD is the complete content of the cell.
            m_only = re.match(
                r"^(?:\*\s+-|-)\s+``(GET|POST|PUT|PATCH|DELETE)``\s*$",
                stripped,
                re.I,
            )
            if m_only:
                prev_method = m_only.group(1).upper()
                continue

            # Path cell directly after a method cell:
            #   "- ``/path/{id}``"
            if prev_method is not None:
                p_only = re.match(r"^-\s+``(/[^`]*)``", stripped)
                if p_only:
                    raw_path = p_only.group(1)
                    norm = normalise_path(raw_path)
                    key = (prev_method, norm)
                    found.setdefault(key, []).append((fpath, lineno))
                    prev_method = None
                    continue
                # If the next non-blank line is not a path cell, reset state.
                if stripped and not stripped.startswith("#"):
                    prev_method = None

    return found


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "paths",
        nargs="*",
        help="RST directories or files to scan (default: docs/source/)",
    )
    parser.add_argument(
        "--strict-undocumented",
        action="store_true",
        help="Exit 1 if any OpenAPI route lacks doc coverage (in addition to phantom routes).",
    )
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parent.parent
    openapi_path = repo_root / "docs" / "openapi.json"

    if not openapi_path.exists():
        print(
            f"check_openapi_refs: ERROR {openapi_path} not found.\n"
            "Run `python scripts/generate_openapi.py` first.",
            file=sys.stderr,
        )
        return 2

    if args.paths:
        search_roots = [Path(p) for p in args.paths]
    else:
        search_roots = [repo_root / "docs" / "source"]

    schema_routes = routes_from_openapi(openapi_path)
    doc_routes_map = routes_from_docs(search_roots)
    doc_routes = set(doc_routes_map.keys())

    # Apply allowlist — remove from both sets so they are never reported.
    schema_routes -= _ALLOWLIST
    doc_routes -= _ALLOWLIST

    # --- Phantom routes: docs reference a route not in the schema ----------
    phantom = sorted(doc_routes - schema_routes)

    # --- Undocumented routes: in schema but not cited anywhere in docs ------
    undocumented = sorted(schema_routes - doc_routes)

    # --- Report -------------------------------------------------------------
    has_error = False

    if phantom:
        has_error = True
        print(f"check_openapi_refs: {len(phantom)} PHANTOM route(s) "
              "(documented but not in OpenAPI schema):\n")
        for method, path in phantom:
            locs = doc_routes_map.get((method, path), [])
            loc_str = ", ".join(
                f"{f.relative_to(repo_root)}:{n}" for f, n in locs[:3]
            )
            print(f"  {method:7} {path}  ({loc_str})")
        print()

    if undocumented:
        level = "ERROR" if args.strict_undocumented else "WARNING"
        if args.strict_undocumented:
            has_error = True
        print(f"check_openapi_refs: {len(undocumented)} {level}: route(s) in schema "
              "but not cited in docs/source/:\n")
        for method, path in undocumented:
            print(f"  {method:7} {path}")
        print()

    if not phantom and not undocumented:
        print(
            f"check_openapi_refs: OK "
            f"({len(schema_routes)} schema routes, "
            f"{len(doc_routes)} cited in docs, 0 phantom, 0 undocumented)"
        )
    elif not has_error:
        print(
            f"check_openapi_refs: OK (0 phantom routes; "
            f"{len(undocumented)} undocumented routes are warnings only)"
        )

    return 1 if has_error else 0


if __name__ == "__main__":
    sys.exit(main())
